name: quakeworx-workshop-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - matplotlib
  - requests
  - numpy
  - scipy
  - obspy
  - pandas
  - cartopy 
  - pycsep
  - ipykernel  # Ensures the environment is available as a Jupyter kernel
  - pip
  - pip:
    - wget
    - usgs-libcomcat
 
